import React from 'react'
import contactvideo from "/Video/contact.mp4"
import BreadCrumb from '../../components/BreadCrumb/BreadCrumb.jsx';
import Builder from '../../components/Builder.jsx';

const PrivacyPolicy = () => {
  return (
    <>
      <div className='w-[100%] lg:h-[50vh] h-60 relative'>
        <video
          src={contactvideo}
          autoPlay
          muted
          loop
          playsInline
          className="w-full h-full object-cover"
        />
        <h1 className='font-bold text-center absolute top-[65%] left-[50%] text-white lg:text-6xl text-3xl transform -translate-x-[50%] -translate-y-[50%] tracking-[3px]'>
          PRIVACY POLICY
        </h1>
        <div className="absolute bottom-2 lg:left-[7%] left-[8%]">
          <BreadCrumb />
        </div>
      </div>

      <div className="p-6 lg:p-16">
        <div className="lg:p-10 border border-black p-4 space-y-6">
          <p className="text-sm text-[#555555] lg:text-base">
            At Propcodes.com, we respect your privacy and are committed to protecting the personal information of all our users, including brokers, builders, owners, and potential buyers or renters (collectively referred to as "Users"). This Privacy Policy outlines how we collect, use, disclose, and safeguard your personal information when you access and use our website, Propcodes.com, and related services (the "Platform").
          </p>
          <p className="text-sm text-[#555555] lg:text-base">
            By using our Platform, you agree to the practices described in this Privacy Policy. If you do not agree with the terms, please do not use the Platform or its services.
          </p>

          <h2 className="font-bold text-xl mt-6 text-[#002a68]">1. Information We Collect</h2>
          <p className="text-sm text-[#555555] lg:text-base">We collect the following types of information when you use our Platform:</p>
          <h3 className="font-semibold mt-2 text-[#002a68]">A. Information You Provide Directly:</h3>
          <ul className="list-disc list-inside ml-4">
            <li className="text-sm text-[#555555] lg:text-base">Personal Details: Name, email address, phone number, company name, and other contact details provided during account registration.</li>
            <li className="text-sm text-[#555555] lg:text-base">Property Details: Information about properties you list, including property type, location, size, amenities, pricing, and photos.</li>
            <li className="text-sm text-[#555555] lg:text-base">Payment Information: While we do not store financial data, we use third-party payment processors to handle payment transactions for premium services.</li>
            <li className="text-sm text-[#555555] lg:text-base">Communication Data: Records of your communications with us, such as inquiries, feedback, support requests, or other interactions via email, phone, or forms.</li>
          </ul>
          <h3 className="font-semibold mt-2 text-[#002a68]">B. Information Collected Automatically:</h3>
          <ul className="list-disc list-inside ml-4">
            <li className="text-sm text-[#555555] lg:text-base">Usage Data: Information about how you interact with the Platform, including search preferences, pages visited, and time spent on the Platform.</li>
            <li className="text-sm text-[#555555] lg:text-base">Device Data: IP address, browser type, operating system, device identifiers, and other technical information.</li>
            <li className="text-sm text-[#555555] lg:text-base">Cookies: We use cookies and similar technologies to recognize you, enhance your user experience, and analyze Platform traffic. You may disable cookies in your browser settings, but certain features may not work as intended.</li>
          </ul>
          <h3 className="font-semibold mt-2 text-[#002a68]">C. Third-Party Data:</h3>
          <p className="text-sm text-[#555555] lg:text-base">We may collect information about you from third-party services, marketing partners, or through leads generated by external advertising platforms.</p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">2. How We Use Your Information</h2>
          <ul className="list-disc list-inside ml-4">
            <li className="text-sm text-[#555555] lg:text-base">Service Provision: To enable you to post property listings, manage your account, and connect with leads.</li>
            <li className="text-sm text-[#555555] lg:text-base">Lead Generation: To provide relevant leads based on your property listings through marketing efforts or third-party applications.</li>
            <li className="text-sm text-[#555555] lg:text-base">Marketing and Promotions: To send you updates, promotions, and recommendations based on your preferences and activities.</li>
            <li className="text-sm text-[#555555] lg:text-base">Platform Improvement: To enhance our services, develop new features, and personalize your experience on the Platform.</li>
            <li className="text-sm text-[#555555] lg:text-base">Analytics and Research: To analyze user behavior, monitor trends, and improve the effectiveness of our marketing efforts.</li>
            <li className="text-sm text-[#555555] lg:text-base">Legal Compliance: To comply with applicable legal obligations, resolve disputes, and enforce our terms of service.</li>
          </ul>

          <h2 className="font-bold text-xl mt-6 text-[#002a68]">3. How We Share Your Information</h2>
          <p className="text-sm text-[#555555] lg:text-base">We may share your personal data in the following circumstances:</p>
          <ul className="list-disc list-inside ml-4">
            <li className="text-sm text-[#555555] lg:text-base">With Other Users: Your contact details and property listings will be visible to potential buyers, renters, or other brokers on the Platform to facilitate transactions.</li>
            <li className="text-sm text-[#555555] lg:text-base">Third-Party Service Providers: We may share your information with trusted third-party service providers, such as payment processors, marketing platforms, or lead-generation applications, to perform services on our behalf.</li>
            <li className="text-sm text-[#555555] lg:text-base">For Legal Purposes: If required by law, regulation, or legal process, we may disclose your information to government authorities or other entities.</li>
            <li className="text-sm text-[#555555] lg:text-base">Business Transfers: In the event of a merger, acquisition, or sale of assets, your information may be transferred to the new owners.</li>
          </ul>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">4. Data Security and Retention</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            We implement commercially reasonable security measures to protect your personal data from unauthorized access, disclosure, or loss. However, no security method is 100% secure, and we cannot guarantee absolute security.
          </p>
          <p className="mt-2 text-sm text-[#555555] lg:text-base">
            We retain your personal information for as long as necessary to provide the services and comply with legal obligations. You may request the deletion of your data by contacting us at [Insert Contact Information], but certain information may be retained for legal or compliance purposes.
          </p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">5. Your Rights</h2>
          <p className="text-sm text-[#555555] lg:text-base">As a user of Propcodes.com, you have the following rights concerning your personal data:</p>
          <ul className="list-disc list-inside ml-4">
            <li className='text-[#555555] lg:text-base text-sm'>Access and Correction: You can access or update your personal information by logging into your account or contacting us.</li>
            <li className='text-[#555555] lg:text-base text-sm'>Opt-Out of Marketing: You may opt out of receiving marketing communications from us at any time by following the unsubscribe instructions in the communication or by contacting us.</li>
            <li className='text-[#555555] lg:text-base text-sm'>Deletion of Data: You may request the deletion of your account or any personal data we hold by contacting our support team.</li>
          </ul>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">6. Cookies and Tracking Technologies</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            We use cookies and similar technologies to track user activity on the Platform, improve your experience, and deliver personalized advertisements. You can manage cookie preferences through your browser settings, but please note that disabling cookies may affect the functionality of the Platform.
          </p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">7. Third-Party Links</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            Our Platform may contain links to third-party websites or services. We are not responsible for the privacy practices of these external sites, and we encourage you to review their privacy policies before sharing your personal information.
          </p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">8. Children's Privacy</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            Our Platform is not intended for users under the age of 18. We do not knowingly collect personal information from minors. If you are under 18, please do not use the Platform or provide any personal information.
          </p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">9. Changes to This Privacy Policy</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            We may update this Privacy Policy from time to time to reflect changes in our practices or applicable laws. We will notify you of any significant updates by posting the revised policy on the Platform. Please review this page periodically for the latest information.
          </p>

          <h2 className="font-bold text-xl text-[#002a68] mt-6">10. Contact Us</h2>
          <p className="text-sm text-[#555555] lg:text-base">
            If you have any questions, concerns, or requests related to this Privacy Policy, please contact us at: info@propcodes.com
          </p>
        </div>
      </div>

      <Builder/>
    </>
  )
}

export default PrivacyPolicy